Sketchware-Pro/Sketchware-Pro

- app/src/main/java/mod/w3wide/menu/MenuBean.java
Intent keys have been replaced with old ones.
Some menu patterns were updated for better selection.
> fix: Intent keys and some menus

- app/src/main/java/com/besome/sketch/beans/ProjectFileBean.java
This file is not fully optimised.
> feat : Removed 'Activity' string from 'Fragments'.

- app/src/main/java/mod/w3wide/menu/MenuBean.java
Added Values from value/values.xml
> Updated MenuBean.java

- README.md
I wanted to add a discord badge too, but the server widget is disabled.
:D
> feat, docs: add title and add some badges

- app/src/main/java/mod/alucard/tn/shrinker/R8Executor.java
fixed the NullPointerException and i add parametrized ArrayList etc...
> fix : some fixed on R8 Executor

- app/src/main/java/mod/agus/jcoderz/variable/DialogImport.java
- app/src/main/java/mod/agus/jcoderz/variable/DialogVariable.java
that custom variable dialog in LogicEditorActivity
> add : agus dialog variable

- app/src/main/java/mod/hey/studios/StringHelper.java
- app/src/main/java/mod/hey/studios/code/ResHelper.java
- app/src/main/java/mod/hey/studios/editor/manage/block/ExtraBlockInfo.java
- app/src/main/java/mod/hey/studios/editor/manage/block/code/ExtraBlockCode.java
- app/src/main/java/mod/hey/studios/editor/manage/block/v2/BlockLoader.java
- app/src/main/java/mod/hey/studios/editor/view/IdGenerator.java
- app/src/main/java/mod/hey/studios/logic/SourceCodeDialog.java
- app/src/main/java/mod/hey/studios/moreblock/ImportMoreblockHelper.java
- app/src/main/java/mod/hey/studios/moreblock/MoreblockValidator.java
- app/src/main/java/mod/hey/studios/moreblock/ReturnMoreblockManager.java
> feat : add some HeyStudios classes

- app/src/main/java/mod/hey/studios/lib/JarCheck.java
- app/src/main/java/mod/hey/studios/lib/LineNumberedTextView.java
> feat : add some HeyStudios lib files

- app/src/main/java/mod/ilyasse/activities/about/AboutModActivity.java
- app/src/main/res/layout-v11/about_moddersview.xml
- app/src/main/res/layout/about.xml
Note: I replaced circleCrop() with CardView because I think that Sketchware uses Glide 3 not Glide 4.
> feat: about activity improvements

- app/src/main/java/a/a/a/uq.java
Added some extra Intent Actions.
> feat: added uq.java

- app/src/main/java/a/a/a/MB.java
This file is for Validators.
tested out.
> feat: added MB.java

- app/src/main/java/mod/w3wide/highlighter/SimpleHighlighter.java
- app/src/main/java/mod/w3wide/highlighter/SyntaxScheme.java
Added `Syntax Highlighter` for `Add Source Directly block` in `Logic Editor`.
> feat: added Syntax Highlighter

- app/src/main/java/mod/hey/studios/util/SystemLogPrinter.java
Added a better source of SystemLogPrinter.java (from the mod.hey.studios package)
> feat: Add source of SystemLogPrinter.java

- app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
- app/src/main/java/mod/hilal/saif/blocks/BlocksHandler.java
- app/src/main/java/mod/w3wide/blocks/ExtraBlocks.java
- app/src/main/java/mod/w3wide/control/logic/LogicClickListener.java
- app/src/main/java/mod/w3wide/menu/ExtraMenuBean.java
- app/src/main/java/mod/w3wide/menu/MenuBean.java
- app/src/main/java/mod/w3wide/variable/DialogCustomList.java
- app/src/main/java/mod/w3wide/variable/DialogCustomVariable.java
> `feat:` added `LogicClickListner`, `Custom List Dialog`, some blocks, menu.
Added `Assets` and `Native Library` selector by menu.
> `improvement:`  improved `Custom Variable Dialog` and codes
> `refactor:` optimized codes by new fields, removed unused methods
> feat, improvement, refactor: blocks and menu system

- app/src/main/java/mod/agus/jcoderz/beans/BroadcastBean.java
- app/src/main/java/mod/agus/jcoderz/beans/ServiceBean.java
- app/src/main/java/mod/agus/jcoderz/beans/ViewBeans.java
- app/src/main/java/mod/agus/jcoderz/component/ManageComponent.java
- app/src/main/java/mod/agus/jcoderz/editor/event/ManageEventComponent.java
- app/src/main/java/mod/agus/jcoderz/lib/ColorScheme.java
- app/src/main/java/mod/agus/jcoderz/lib/FilePathUtil.java
- app/src/main/java/mod/agus/jcoderz/lib/FileResConfig.java
- app/src/main/java/mod/agus/jcoderz/lib/FileUtil.java
- app/src/main/java/mod/agus/jcoderz/lib/HighlighterEditText.java
- app/src/main/java/mod/agus/jcoderz/lib/TypeClassWidget.java
- app/src/main/java/mod/agus/jcoderz/variable/DialogImport.java
- app/src/main/java/mod/agus/jcoderz/variable/DialogVariable.java
- app/src/main/java/mod/alucard/tn/apksigner/ApkSigner.java
- app/src/main/java/mod/alucard/tn/shrinker/R8Executor.java
Some cleanups and optimizations on `mod/agus` and `mod/alucard`
Note: I haven't tested this, but looking from the changes, there shouldn't be any difference
> Some cleanups and optimizations

- app/src/main/java/dev/aldi/sayuti/block/ExtraBlockFile.java
- app/src/main/java/mod/hey/studios/StringHelper.java
- app/src/main/java/mod/hey/studios/activity/SrcCodeEditor.java
- app/src/main/java/mod/hey/studios/activity/managers/assets/ManageAssetsActivity.java
- app/src/main/java/mod/hey/studios/activity/managers/java/ManageJavaActivity.java
- app/src/main/java/mod/hey/studios/activity/managers/nativelib/ManageNativelibsActivity.java
- app/src/main/java/mod/hey/studios/build/BuildSettingsDialog.java
- app/src/main/java/mod/hey/studios/code/SrcCodeEditor.java
- app/src/main/java/mod/hey/studios/code/SrcCodeEditorDialog.java
- app/src/main/java/mod/hey/studios/editor/manage/block/code/ExtraBlockCode.java
- app/src/main/java/mod/hey/studios/editor/manage/block/v2/BlockLoader.java
- app/src/main/java/mod/hey/studios/editor/view/IdGenerator.java
- app/src/main/java/mod/hey/studios/lib/JarCheck.java
- app/src/main/java/mod/hey/studios/lib/prdownloader/PRDownloader.java
- app/src/main/java/mod/hey/studios/logic/SourceCodeDialog.java
- app/src/main/java/mod/hey/studios/moreblock/ImportMoreblockHelper.java
- app/src/main/java/mod/hey/studios/moreblock/MoreblockValidator.java
- app/src/main/java/mod/hey/studios/moreblock/ReturnMoreblockManager.java
- app/src/main/java/mod/hey/studios/project/ProjectSettings.java
- app/src/main/java/mod/hey/studios/project/backup/BackupFactory.java
- app/src/main/java/mod/hey/studios/project/backup/BackupRestoreManager.java
- app/src/main/java/mod/hey/studios/project/custom_blocks/CustomBlocksDialog.java
- app/src/main/java/mod/hey/studios/project/library/LibraryDownloader.java
- app/src/main/java/mod/hey/studios/project/proguard/ProguardHandler.java
- app/src/main/java/mod/hey/studios/project/stringfog/ManageStringfogActivity.java
- app/src/main/java/mod/hey/studios/project/stringfog/StringfogHandler.java
- app/src/main/java/mod/hey/studios/util/Helper.java
- app/src/main/java/mod/hey/studios/util/ProjectFile.java
- app/src/main/java/mod/hey/studios/util/SystemLogPrinter.java
Cleanup and optimizations on `mod/hey`
> Another cleanup

- README.md
- app/src/main/java/com/sketchware/remod/Resources.java
- app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
- app/src/main/java/mod/w3wide/blocks/ExtraBlocks.java
- app/src/main/java/mod/w3wide/control/logic/SourceHandler.java
- app/src/main/java/mod/w3wide/menu/ExtraMenuBean.java
`feat:` added Add Source Directly Dialog with Syntax Highlighter.
`feat:` added new Command Blocks
> feat: added ASD Dialog, new Command Blocks

- app/src/main/java/com/besome/sketch/design/DesignActivity.java
- app/src/main/java/mod/nethical/mod/Cleaner.java
- app/src/main/res/layout/design.xml
just Added a Project trash cleaner . It deletes all trash files inside the [projectnum]/bin folder except the classes folder as deleting it will decrease the compilation time .
> Feat: Added feature to clean project trash

- app/src/main/java/com/besome/sketch/design/DesignActivity.java
Now subtitle will show the project id
> feat: set a role to the subtitle

- app/src/main/res/values-es/strings.xml
Nothing to add, just a small change.
> feat: A fix in deny value when searching for files

- app/src/main/java/com/besome/sketch/design/DesignActivity.java
feat: added Install Apk Option in the `DesignActivity`
> feat: added Install Apk Option

- app/src/main/java/mod/hilal/saif/activities/tools/BlocksManager.java
feat: show an error when the code is not in formed well
> feat: show an error when the code is not in formed well

- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
Fixed ConcurrentModificationException error
> Fix: fixed crash in Local Library Manager

- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
This should fix checkbox error.
> Fix: Local Library Manager

- app/src/main/java/mod/hey/studios/project/backup/BackupRestoreManager.java
> feat: Update Backup Dialog

- app/src/main/java/mod/hey/studios/editor/manage/block/code/ExtraBlockCode.java
- No more % error when String.format
- return /* Error: (error)*/ when it get error
> feat: Catch Custom Blocks' spec errors

- app/src/main/java/mod/hey/studios/logic/SourceCodeDialog.java
Improve SourceCodeDialog by adding CodeEditor: 
- Faster
- Cleaner
- Zoomable
> feat: Improve SourceCodeDialog

- app/src/main/java/a/a/a/Ox.java
added the ability to remove "orientation" attribute from LinearLayout.
> feat: Allow removing orientation tag with inject

- app/src/main/java/mod/ilyasse/activities/about/AboutModActivity.java
- app/src/main/res/layout/about_changelog.xml
Nothing To Put Here. Changes have been tested and It Works
> fix: Replaced Missing Resource Id's With Tags; Fixed Header Type Not Appearing

- app/src/main/java/mod/ilyasse/activities/about/AboutModActivity.java
- app/src/main/res/layout/about.xml
- app/src/main/res/layout/about_changelog.xml
This makes some important fixes to AboutModActivity. Opened a PR because I wasn't sure of the ripple effects, but maybe y'all have more to comment on.
> feat: Improve AboutModActivity

- aboutus.json
> misc: Update AboutMod Description

- app/src/main/java/com/besome/sketch/common/SrcViewerActivity.java
-Asynchronous source generation
-Better code viewer (Sora editor)
-Preserves the original looks
Feels 50% faster ngl
> feat: Create Vastly Improved SrcViewerActivity.java

- app/src/main/java/a/a/a/GC.java
- app/src/main/java/com/besome/sketch/MainActivity.java
- app/src/main/res/layout-v22/myprojects.xml
- app/src/main/res/layout/myprojects.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
Just some cleanups without much actual benefits.
But it fixes some weird behavior's
> misc: Improve projects fragment

- app/src/main/java/com/besome/sketch/editor/manage/library/firebase/ManageFirebaseActivity.java
- app/src/main/java/mod/hey/studios/project/backup/BackupFactory.java
- app/src/main/java/mod/hilal/saif/activities/tools/ConfigActivity.java
How cool is that, I know right.
PR Is Self Explanatory, Or look at the images
**Input:**
**Output:**
> feat: You can now modify the filename format of project backups

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/besome/sketch/SketchApplication.java
- app/src/main/java/com/besome/sketch/tools/CollectErrorActivity.java
- app/src/main/java/mod/RequestNetwork.java
- app/src/main/java/mod/RequestNetworkController.java
just change webhook_url with actual discord webhook url through github actions or manually for release idk
> feat: sending crash logs to discord through webhooks

- app/src/main/java/com/besome/sketch/beans/ComponentBean.java
- app/src/main/java/com/besome/sketch/editor/manage/library/firebase/ManageFirebaseActivity.java
> Add new docs and update exisiting ones

- app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
> bug fix when lib not download

- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
- app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
Fixes #913 and #908 and these reports
> Greatly reduce time complexity with androidx dependencies

- app/src/main/java/a/a/a/dt.java
- app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
- app/src/main/java/com/besome/sketch/editor/manage/ManageCollectionActivity.java
- app/src/main/java/com/besome/sketch/editor/manage/ShowMoreBlockCollectionActivity.java
- app/src/main/java/mod/hey/studios/moreblock/ReturnMoreblockManager.java
- app/src/main/java/mod/hey/studios/moreblock/importer/MoreblockImporterDialog.java
- app/src/main/java/mod/jbk/util/BlockUtil.java
- app/src/main/res/layout/manage_collection_more_block_list_item.xml
- app/src/main/res/layout/manage_collection_popup_import_more_block_list_item.xml
> Fix moreblock collection preview in list item

- app/src/main/java/a/a/a/Jx.java
- app/src/main/java/a/a/a/Ox.java
- app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
- app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
This will not declare field and initialize the view when inject property has attribute to replace 'android:id'
> Remove views field and initialization

- app/src/main/java/dev/aldi/sayuti/editor/injection/AddCustomAttributeActivity.java
- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageCustomAttributeActivity.java
- app/src/main/java/mod/hilal/saif/activities/android_manifest/AndroidManifestInjection.java
- app/src/main/java/mod/hilal/saif/activities/android_manifest/AndroidManifestInjectionDetails.java
- app/src/main/java/mod/khaled/logcat/LogReaderActivity.java
- app/src/main/java/mod/remaker/view/CustomAttributeView.java
- app/src/main/res/layout/activity_logcatreader.xml
- app/src/main/res/layout/custom_view_attribute.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
Some fixes at the request of contributors.
> Some fixes

- app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
This pr fix this issue
https://discord.com/channels/790686719753846785/790687919559278612/1211545716258775080
> fix: instance of compound button not showing in %m.checkbox

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
- app/src/main/res/values/styles.xml
This changes will  prevent from using material3 in the view editor
> Use default view editor theme

- app/src/main/java/mod/hilal/saif/blocks/BlocksHandler.java
> Fix some block names

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
- app/src/main/java/mod/elfilibustero/sketch/beans/ResourceBean.java
- app/src/main/java/mod/elfilibustero/sketch/lib/utils/InjectAttributeHandler.java
- app/src/main/java/mod/elfilibustero/sketch/lib/utils/ResourceUtil.java
> Font previewer

- app/src/main/java/com/besome/sketch/tools/CollectErrorActivity.java
Its pretty annoying to read incomplete error messages from screenshots
> Add copy error to clipboard feature in `CollectErrorActivity`

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
- app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemMaterialButton.java
materialbutton injection preview in the views pane
> Views injector preview (Material Button)

- app/src/main/java/a/a/a/aB.java
- app/src/main/java/com/besome/sketch/design/DesignActivity.java
- app/src/main/java/mod/trindadedev/tools/ApkSignatures.java
- app/src/main/java/mod/trindadedev/tools/ApkUtils.java
- app/src/main/res/values/strings.xml
I also added a method to make the message text of the aB dialog selectable.
Preview:
> feat: add ApkSignatures to obtain sha-1 & sha-256

- app/src/main/java/com/besome/sketch/editor/logic/PaletteBlock.java
> chore: Use CardView in PalleteBlock instead backgroundResource in TextView

- app/src/main/res/drawable/rounded_bottom_sheet.xml
- app/src/main/res/values/styles_new.xml
- app/src/main/res/values/themes.xml
> fix: Wrong navigationBar color in bottomSheets

- app/src/main/java/com/besome/sketch/help/ProgramInfoActivity.java
- app/src/main/java/com/besome/sketch/lib/ui/PropertyOneLineItem.java
- app/src/main/java/com/besome/sketch/lib/ui/PropertyTwoLineItem.java
- app/src/main/java/mod/ilyasse/activities/about/AboutActivity.java
- app/src/main/res/layout/program_info.xml
- app/src/main/res/layout/program_info_item.xml
- app/src/main/res/layout/program_info_two_line_item.xml
the name PR speaks for itself.
> fix, feat: Redesign program info activity

- app/src/main/AndroidManifest.xml
- app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
- app/src/main/java/mod/bobur/StringEditorActivity.java
- app/src/main/res/layout/string_editor.xml
- app/src/main/res/layout/string_editor_item.xml
- app/src/main/res/layout/view_string_editor_add.xml
This pull request originally belongs to @Bobur-777.
PR: #1296
> Added strings editor

- app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java
- app/src/main/res/layout/blocks_manager_creator.xml
Use Rs class instead of 9 patch for block preview
> Block manager preview

- app/src/main/java/a/a/a/Ox.java
- app/src/main/java/mod/elfilibustero/sketch/lib/utils/InjectAttributeHandler.java
Prevent generation of attribute when inject property has it
> Inject property

- app/src/main/java/mod/hey/studios/project/backup/BackupFactory.java
- app/src/main/java/mod/hey/studios/project/custom_blocks/CustomBlocksManager.java
This will resolve the issue mentioned here: https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1294. However, it will only work in a new backup of the project and if the custom blocks are already available in your project.
> Fix custom blocks

- app/src/main/java/dev/aldi/sayuti/editor/injection/AddCustomAttributeActivity.java
This will fix the issue https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1224
> Fix appcompat attributes deletion

- app/src/main/java/a/a/a/Ox.java
Collapsing toolbar not being added when built-in toolbar is disabled
> Fix CollapsingToolbarLayout

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
This pr is supposed to solve this issue https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1219
However, this changes need more testing.
> Resolve issue with drag and drop

- app/src/main/java/a/a/a/Jx.java
- app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java
- app/src/main/res/layout/blocks_manager_creator.xml
Added a way to add imports for custom blocks
> Custom Block Imports

- app/src/main/java/dev/aldi/sayuti/editor/manage/LibraryDownloaderDialogFragment.java
- app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt
Fix Crashing during downloading library
> Fix: Library download Problem and unziping

- app/src/main/res/values-night/colors.xml
> fix: `view_property_tab_active_text` color in dark mode

- app/src/main/java/a/a/a/Fx.java
This PR resolves issues : #1421, #1414, #1397, #1386
> fix Stuck on `Deleting Temporary Files`

- app/src/main/java/mod/hey/studios/activity/managers/assets/ManageAssetsActivity.java
> feat: Allow open another text files

- about.json
> Added Archived Team and Myself

- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
- Fixed ConcurrentModificationException caused by modifying the list while iterating
- The old method suffered from unnecessary threads, disk I/O, and adapter recreation, leading to delays and poor performance
> fix, perf: optimize Local Library Search

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
Initially this changes was based on decompiled ViewPane 
This improvement handles the provided project on this issue too https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1219
> feat: Improved droppable location for LinearLayout in ViewPane

- app/src/main/java/com/besome/sketch/editor/manage/library/LibraryItemView.java
- app/src/main/java/com/besome/sketch/editor/manage/library/ManageLibraryActivity.java
- app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
- app/src/main/java/mod/hilal/saif/activities/tools/AppSettings.java
- app/src/main/java/pro/sketchware/fragments/settings/block/selector/BlockSelectorAdapter.java
- app/src/main/java/pro/sketchware/fragments/settings/block/selector/details/BlockSelectorDetailsAdapter.java
- app/src/main/java/pro/sketchware/fragments/settings/events/EventsManagerFragment.java
- app/src/main/java/pro/sketchware/fragments/settings/events/details/EventsManagerDetailsFragment.java
- app/src/main/java/pro/sketchware/utility/UI.java
- app/src/main/res/drawable/shape_alone.xml
- app/src/main/res/drawable/shape_bottom.xml
- app/src/main/res/drawable/shape_top.xml
- app/src/main/res/layout/manage_library_base_item.xml
- app/src/main/res/layout/view_item_local_lib.xml
I preferred to open a PR, in case you don't like it, or want some changes.
> Some UI Improvements 

- app/src/main/java/mod/khaled/logcat/LogReaderActivity.java
- app/src/main/java/pro/sketchware/utility/FileUtil.java
- app/src/main/res/menu/menu_logcat.xml
> feat : Export Logcat for logcat reader

- app/src/main/java/mod/hilal/saif/activities/android_manifest/AndroidManifestInjection.java
- app/src/main/java/pro/sketchware/fragments/settings/events/EventsManagerFragment.java
- app/src/main/java/pro/sketchware/fragments/settings/events/creator/EventsManagerCreatorFragment.java
- app/src/main/res/layout/blocks_manager_creator.xml
- app/src/main/res/layout/dialog_add_new_listener.xml
- app/src/main/res/layout/dialog_block_configuration.xml
- app/src/main/res/layout/fragment_events_manager_creator.xml
**Screenshots:**
1 - https://t.me/sketchwarepro/311114
2 - https://t.me/sketchwarepro/311071
Maybe my code not clear but result is good : )
> fix: Some ui fixes for small screen devices

- app/src/main/java/a/a/a/Jx.java
- app/src/main/java/mod/pranav/viewbinding/ViewBindingBuilder.kt
:> I see this bug on when I export sk project to android studio and I need to import binding classes in all my activities, because i changed it and no problems
> fix: Correct package name for View Binding classess

- app/src/main/java/com/besome/sketch/projects/MyProjectSettingActivity.java
Someone reverted this behaviour
> Enable viewbinding for new projects

- app/src/main/java/a/a/a/Jx.java
- app/src/main/java/mod/pranav/viewbinding/ViewBindingBuilder.kt
> Revert "fix: Correct package name for View Binding classess"

- app/build.gradle
- app/src/main/assets/oss.txt
- app/src/main/java/a/a/a/Lx.java
- app/src/main/java/a/a/a/yq.java
- app/src/main/java/com/besome/sketch/editor/manage/library/firebase/ManageFirebaseActivity.java
- app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java
- app/src/main/java/mod/hey/studios/activity/managers/assets/ManageAssetsActivity.java
- app/src/main/java/mod/hey/studios/activity/managers/java/ManageJavaActivity.java
- app/src/main/java/mod/hey/studios/activity/managers/nativelib/ManageNativelibsActivity.java
- app/src/main/java/mod/hey/studios/project/backup/BackupRestoreManager.java
- app/src/main/java/mod/hey/studios/project/proguard/ProguardHandler.java
- app/src/main/java/mod/hilal/saif/activities/tools/AppSettings.java
- app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerDetailsActivity.java
- app/src/main/java/pro/sketchware/activities/editor/component/AddCustomComponentActivity.java
- app/src/main/java/pro/sketchware/activities/editor/component/ManageCustomComponentActivity.java
- app/src/main/java/pro/sketchware/fragments/settings/block/selector/BlockSelectorManagerFragment.java
- app/src/main/java/pro/sketchware/fragments/settings/events/EventsManagerFragment.java
- app/src/main/java/pro/sketchware/menu/ExtraMenuBean.java
- app/src/main/java/pro/sketchware/widgets/WidgetsCreatorManager.java
- build.gradle
- M3 Expressive based FilePicker implementation
- Updates some old licenses in oss.txt
- Updates compileSdk to 36
> New file picker implementation

- app/src/main/java/pro/sketchware/activities/about/fragments/BetaChangesFragment.java
- AboutActivity.java got some fixes and optimizations
- BetaChangesFragment.java and ChangeLogFragment.java got fixes and optimization
> refactor, fix and optimize about activites and fragments

- app/src/main/java/pro/sketchware/activities/main/activities/MainActivity.java
this will prevent app crash in case firebase isnt configured or didnt initialised at startup for project store
ps : the crash is happening Already for forks contributors doesnt have access to hiden files aka secrets
the pr is working now 👌
> fix: check firebase init before calling firebase messaging service

- app/src/main/java/a/a/a/yq.java
- app/src/main/java/com/besome/sketch/projects/MyProjectSettingActivity.java
- app/src/main/java/com/besome/sketch/projects/ThemeManager.java
- app/src/main/java/com/besome/sketch/projects/ThemePresetAdapter.java
- app/src/main/java/mod/hey/studios/lib/code_editor/CodeEditorLayout.java
- app/src/main/java/mod/hey/studios/lib/code_editor/ColorScheme.java
- app/src/main/java/mod/hey/studios/lib/code_editor/ColorTheme.java
- app/src/main/res/drawable/theme_preset_item_selector.xml
- app/src/main/res/layout/myproject_setting.xml
- app/src/main/res/layout/theme_preset_item.xml
- app/src/main/res/values/strings.xml
A comprehensive theme management system that allows users to customize the visual appearance of their Android projects by selecting from a curated collection of Material Design 3 color schemes or generating unique random color combinations. The system offers 12 pre-made themes, including variants of Material Design (Purple, Blue, Green, Red, Orange, Teal, Indigo, Pink), as well as dark and light themes. Each theme consists of five coordinated colors: primary, primary dark, accent, control accent, and control normal. The random theme generator creates harmonious color palettes using HSV color space algorithms combined with complementary color theory, ensuring visually appealing and accessible color combinations for Android apps.
**Key Features:**
* Pre-built Material Design 3 themes with …
> Material design theme customizer

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
this will fix the kotlin compiler issues and add more compatibilities with newer dependencies .
also will fix this issue https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1813
source for kotlinc :
https://github.com/waelchateur/kotlinc-for-sketchware
> upgrade kotlinc version to 2.1.21

- app/src/main/java/com/besome/sketch/editor/view/ViewPane.java
Reverting [this](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/f9379727d20e3c581dbd1305dead70c4ec7d9b1a)
> fix: View not selectable when Disabled
