app/src/main/java/mod/w3wide/dialog/SketchDialog.java

I have removed default string for Neutral Button because it was automatically added.

fix: Automatic Neutral Button

---

README.md

reason:
I do that to make the source code map more clear

fix: change source code map to a table

---

app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java

**fix: no more local_library file if launched from mod configuration.**
Selecting or opening local library manager from Mod Configuration will no longer create ```.sketchware\data\system\local_library```
Benefits: Um, YES
**feat: Added reset function in LocaLibrary manager**
Now users can reset their projects ```local_library``` file from Local Library Manager.
It's useful in case the project was using a library that was deleted.
In that case, resetting the ```local_library``` file to ```[]``` would remove all those previously selected libraries that were deleted.
This is kinda impotent

feat, fix: Local library Manager reset function, stop creating file

---

app/src/main/java/a/a/a/yq.java
app/src/main/java/com/besome/sketch/design/DesignActivity.java

I added a new option to show Java source code of a single activity. No need to open SrcCodeViewer -which can be slow in large projects- just to see a source code of an activity anymore, all you need to do is to open the activity you want to show its source, then click on the "compiler option" button next to the "run" button and select "show source code".

feat: add option to show the source code of a single activity.

---

app/src/main/java/com/besome/sketch/DebugActivity.java

findViewById after dialog.show when?
also why null checks?

fix:Make DebugActivity text actually selectable,Cleanup unnecessary null checks

---

app/src/main/java/com/besome/sketch/MainActivity.java
app/src/main/java/mod/hilal/saif/activities/tools/ConfigActivity.java

If no storage perms , don't try to read for custom config,
Fixes startup crash

fix: Check for storage perms before reading config

---

app/src/main/java/a/a/a/Jx.java

fix: Use getActivity() in fragments for AlertDialog

---

app/src/main/res/layout/about_changelog.xml
app/src/main/res/layout/about_moddersview.xml

I fixed an issue happening in old android (before android 7), the images at about screen had shandows but not images.

fix: Images not loading in about screen in old android versions

---

app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt

Fixes random unexpected crashes while parsing maven metadata on some cases
Reproduction dependencies:
org.apache.maven:maven-artifact:3.8.1
Source: https://stackoverflow.com/a/16299661

Fix a rare crash with parsing maven metadata

---

app/src/main/java/mod/hey/studios/project/proguard/ProguardHandler.java

This fix allows the use of @JavascriptInterface methods without removing the protection of evals.

fix: Now the javascript functions are not in conflict with proguard

---

app/build.gradle

Bumps `com.github.iyxan23.zipalign-java` dependency to the latest version
This added the ability to align `.so` files into 4KiB page boundaries.

Bump `zipalign-java` dependency to 1.1.1

---

app/build.gradle

A patch update that fixes overflowing issues for apk with a lot of large `.so` files.

Bump iyxan23/zipalign-java to v1.1.2

---

app/build.gradle
app/src/main/java/dev/aldi/sayuti/editor/manage/ManageLocalLibraryActivity.java
app/src/main/java/mod/pranav/dependency/resolver/DependencyResolver.kt

This is a subset of #1141 with the unrelated dependency version bumps removed. It also fixes compiling downloaded Local libraries, which together with the sped up dependency resolver allowed me to create a project that uses `com.google.android.material:material:1.12.0` successfully.
Comments, anyone?
Fixes #1139.

DependencyResolver: Update version and fix d8 invocation (rfc)

---

app/src/main/assets/debug/DebugActivity.java
app/src/main/assets/debug/SketchApplication.java

fixes #1140 
DebugActivity now launched every time using intent because,
AlarmManager is unreliable
Also changed the crash message view from dialog to a bi directional scroll
Profit: formatted crash logs

fix,feat: Improve DebugActivity

---

app/src/main/java/mod/hey/studios/build/BuildSettingsDialog.java

fix view colors on BuildSettingsDialog and add a class to "facilitate" the use of TextInputLayout & TextInputEditText  in java or kt class 
See:

fix view colors on BuildSettingsDialog

---

app/src/main/java/a/a/a/br.java

This update might fix the crash when adding a new component event. I moved the code to their adapter, so it no longer depends on checking the type with instanceof. This should make the event more reliable.

fix: Crash when adding a new component in certain cases

---

app/src/main/java/com/besome/sketch/design/DesignActivity.java
app/src/main/java/mod/agus/jcoderz/editor/manage/resource/ManageResourceActivity.java

Refresh view editor only when navigating from Resources Manager, instead of onResume
This caused by the previous pr
https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1305

Small adjustment

---

app/src/main/java/dev/aldi/sayuti/editor/injection/AddCustomAttributeActivity.java

This pull request resolves an `issue` with the AppCompat Injection Manager, where the edit dialog would always modify "Toolbar attributes" `regardless of the selected one` . This issue has been `fixed` by using `originalPosition`, similar to the existing logic in the delete function, to accurately locate and edit the correct attribute.

Fix AppCompat Injection Manager

---

app/src/main/java/a/a/a/Fx.java

Replaced `%d` with `%s` for proper formatting of `String` (`bean.id`) in the loop block, preventing `crashes` while showing the source code or building the project

fix: crash when using loop block in `a.a.a.Fx`

---

app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java

With this fix, the blockSelectorMenu now correctly retrieves and displays the widget IDs as expected

Fix logic error in `blockSelectorMenu.View` prevent empty widget ID list

---

app/src/main/java/a/a/a/Ox.java
app/src/main/java/pro/sketchware/tools/ViewBeanFactory.java

This change fixes parsing in the XML editor for list widgets like RecyclerView by using the tools:listitem attribute it'll recognize listitem as the customView.

Fix list widget custom view in Direct XML Editor

---

app/src/main/res/layout/icon_creator_activity.xml

- The HorizontalScrollView that previously wrapped the background selection buttons (bg_type) has been removed, which eliminates horizontal scrolling. The scroll is unnecessary as there are only two options, they would never leave the layout.
- The width of the MaterialButtonToggleGroup has been changed from wrap_content to match_parent, making it take up the entire available width.
- Buttons within the toggle group (bg_color and bg_gradient) now use layout_width="0dp" and layout_weight="1", ensuring they are evenly distributed within the container instead of using wrap_content.
- Unnecessary lines have been removed and the layout has been restructured for better alignment and organization.
- These changes will likely improve usability by making the buttons evenly spaced without requiring …

feat: MaterialButtonToggleGroup.

---

app/src/main/java/a/a/a/Fx.java
app/src/main/java/a/a/a/Jx.java
app/src/main/java/a/a/a/Lx.java
app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java
app/src/main/java/mod/agus/jcoderz/editor/event/ManageEvent.java
app/src/main/res/layout/dialog_project_settings.xml

- Changed the implementation of viewBinding so that `binding.` is no longer stored as part of the id when selecting a widget from the block selector menu. Instead, during source code generation, it checks each param type, and if it's a widget, it dynamically adds `binding.`
- This update allows enabling or disabling the feature anytime without issues, unlike the previous approach, whether for `new or old projects`
- Note: Widgets used in `ASD` will require manual adjustment
- I've tested it with a big project from Sketchub, and it's working perfectly. Just need to double-check everything to make sure I didn’t miss anything
- Also fixed a few bugs, like missing imports for some adapters and listeners

fix: refine viewBinding implementation in block selector menu

---

app/src/main/java/pro/sketchware/fragments/settings/block/selector/BlockSelectorManagerFragment.java

fixed an issue where editing a block selector reversed the title and name values

Fixed selector edit fonction saving title and name in wrong order

---

app/src/main/java/com/besome/sketch/editor/logic/PaletteBlock.java

Previously, screen readers would announce block names (e.g., "SetActivityTitle") in a misparsed order (e.g., "Activity, title, set"). This was likely due to default accessibility behavior splitting the CamelCase name and reordering it.
This commit addresses the issue by modifying `PaletteBlock.java`:
1. A helper function `generateContentDescription(String name)` was added to convert CamelCase/PascalCase names into a space-separated format (e.g., "SetActivityTitle" becomes "Set Activity Title").
2. The methods responsible for creating block views (`Rs` instances) now use this helper function to generate a `contentDescription` from the block's opCode (which typically holds the CamelCase name).
3. This generated `contentDescription` is then explicitly set on the block view, ensuring screen …

Fix: Correct screen reader announcement order for blocks

---

app/src/main/java/mod/hilal/saif/asd/AsdDialog.java

this will solve the duplicate usage of the formatter each time the editor opned

fix: resolve formating behaviour in Code editor

---

app/src/main/java/com/besome/sketch/tools/CollectErrorActivity.java

The crash dialog is not longer cancelable.

fix: crash dialog is now uncancelable

---

app/src/main/java/mod/hey/studios/code/SrcCodeEditor.java

- fixed common issue where XML declaration lacks a newline before the root element when using codeeditor prettyPrint option for xml code
- Improved output for readability with multiline XML
- add support for one-liner and nested XML formating

feat: improve XML prettyprint option with proper formating

---

app/src/main/java/a/a/a/Lx.java
app/src/main/java/a/a/a/yq.java

`feat: Set appcompat version to 1.7.1 in Lx.getBuildGradleString.`
`feat: Set firebase-bom version to 34.1.0 in Lx.getBuildGradleString.`
`feat: Set gradle version to 8.12.0 in yq.h.`
`feat: Set google-services version to 4.4.3 in yq.h.`
`feat: Removed JCenter in Lx.c.`
Some things are outdated and cause errors when used on Android Studio.

Fix when using source code for Android Studio

---

app/build.gradle

What’s new in Material 1.14.0-alpha02 → 1.14.0-alpha04?
1. 1.14.0-alpha02 — Jun 18, 2025
compileSdk → 35.
androidx.core bumped; dependency updates.
AppBar / BottomSheet bug fixes + accessibility (half-expanded state).
Catalog/demo fixes; HideOnScrollBehavior fixes. 
2. 1.14.0-alpha03 — Jul 21, 2025
compileSdk 35 note.
BottomSheet handle keyboard support.
Accessibility & demo updates; LoadingIndicator static drawable + animation fixes.
MaterialCardView keyboard selection; ProgressIndicator API improvements. 
3. 1.14.0-alpha04 — Aug 20, 2025
ExposedDropdownMenu keyboard support.
Lists: segmented list style + ListItemViewHolder/demo.
LoadingIndicator: showDelay & minHideDelay.
TextInputLayout/tooltips, TimePicker keyboard support, TopAppBar nav circle background.
AGP & Gradle bumps. …

featuring latest material dependencies update of alpha channel
